# sops configuration
keys:
  - &my-thinkpad age1jqemx6vsd80dl3lwuyxmv456lujxcaty6sj889n4r9znpuydevksrt0jw8
  - &framework-16 age1hfawmdwtlzq2sc9vldxm789d8c2vfq0m2av5gle43jkh0cq5avhqwe3a49

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *my-thinkpad
          - *framework-16
