{ config, lib, pkgs, ... }:

let
  c = config.lib.stylix.colors;

  themeCss = ''
    /* Stylix-generated Obsidian theme */

    .theme-dark, .theme-light {
      --background-primary:         #${c.base00};
      --background-primary-alt:     #${c.base00};
      --background-secondary:       #${c.base01};
      --background-secondary-alt:   #${c.base01};
      --text-normal:                #${c.base05};

      --text-selection:             #${c.base02};
      --background-modifier-border: #${c.base03};

      --text-title-h1: #${c.base08};
      --text-title-h2: #${c.base0B};
      --text-title-h3: #${c.base0A};
      --text-title-h4: #${c.base0D};
      --text-title-h5: #${c.base0E};
      --text-title-h6: #${c.base0E};

      --text-link:               #${c.base0D};
      --text-accent:             #${c.base0D};
      --text-accent-hover:       #${c.base0D};
      --interactive-accent:      #${c.base0D};
      --interactive-accent-hover:#${c.base0D};

      --text-muted: color-mix(in srgb, #${c.base05} 70%, transparent);
      --text-faint: color-mix(in srgb, #${c.base05} 55%, transparent);

      --code-normal: #${c.base0C};

      --text-error:       #${c.base08};
      --text-error-hover: #${c.base08};
      --text-success:     #${c.base0B};

      --tag-color:      #${c.base0C};
      --tag-background: #${c.base03};

      --graph-line:            #${c.base03};
      --graph-node:            #${c.base0D};
      --graph-node-focused:    #${c.base0D};
      --graph-node-tag:        #${c.base0C};
      --graph-node-attachment: #${c.base0B};
    }

    .cm-header-1, .markdown-rendered h1 { color: var(--text-title-h1); }
    .cm-header-2, .markdown-rendered h2 { color: var(--text-title-h2); }
    .cm-header-3, .markdown-rendered h3 { color: var(--text-title-h3); }
    .cm-header-4, .markdown-rendered h4 { color: var(--text-title-h4); }
    .cm-header-5, .markdown-rendered h5 { color: var(--text-title-h5); }
    .cm-header-6, .markdown-rendered h6 { color: var(--text-title-h6); }

    .markdown-rendered code { color: #${c.base0C}; }

    .cm-s-obsidian span.cm-keyword  { color: #${c.base08}; }
    .cm-s-obsidian span.cm-string   { color: #${c.base0B}; }
    .cm-s-obsidian span.cm-number   { color: #${c.base0A}; }
    .cm-s-obsidian span.cm-comment  { color: #${c.base03}; }
    .cm-s-obsidian span.cm-operator { color: #${c.base0D}; }
    .cm-s-obsidian span.cm-def      { color: #${c.base0D}; }

    .markdown-rendered a { color: var(--text-link); }
    .markdown-rendered blockquote { border-left-color: #${c.base0D}; }

    .workspace-leaf.mod-active .workspace-leaf-header-title,
    .nav-file-title.is-active,
    .search-result-file-title {
      color: var(--interactive-accent);
    }
  '';

  # Write the generated CSS to a stable location in the nix store
  themeCssFile = pkgs.writeText "obsidian-stylix-theme.css" themeCss;

  manifest = builtins.toJSON {
    name        = "Stylix";
    version     = "1.0.0";
    minAppVersion = "0.16.0";
    description = "Generated by Stylix";
    author      = "Stylix";
  };

  manifestFile = pkgs.writeText "obsidian-stylix-manifest.json" manifest;
in
{
  # Deploy the theme into every vault listed in obsidian.json on each activation.
  home.activation.obsidianTheme = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    OBSIDIAN_JSON="$HOME/.config/obsidian/obsidian.json"
    if [[ -f $OBSIDIAN_JSON ]]; then
      ${lib.getExe pkgs.jq} -r '.vaults | values[].path' "$OBSIDIAN_JSON" | while read -r vault; do
        [[ -d $vault/.obsidian ]] || continue
        theme_dir="$vault/.obsidian/themes/Stylix"
        $DRY_RUN_CMD mkdir -p "$theme_dir"
        $DRY_RUN_CMD install -m 644 ${themeCssFile} "$theme_dir/theme.css"
        $DRY_RUN_CMD install -m 644 ${manifestFile} "$theme_dir/manifest.json"
      done
    fi
  '';
}
